spring:
  application:
    name: server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:}

naver:
  oauth:
    client-id: ${NAVER_CLIENT_ID:}
    client-secret: ${NAVER_CLIENT_SECRET:}
    redirect-uri: ${NAVER_REDIRECT_URI:}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:}
    region: ${AWS_REGION:ap-northeast-2}
    public-base-url: ${AWS_S3_PUBLIC_BASE_URL:}
